# 指定博客源码分支，因人而异。hexo博客源码托管在独立repo则不用设置此项
branches:
  only:
    - blog

language: node_js
node_js:
  - lts/*
cache:
  directories:
    - node_modules

install:
  - npm install
script:
  - npm run build
  - cd ${FOLDER}
  - git init
  - git config user.name ${UID}
  - git config user.email ${EMAIL}
  - git add .
  - git commit -m "${MESSAGE}"
  - git push --force --quiet https://${TOKEN}@${GIT_URI}.git master:${BRANCH}
